name: spreadsheet_decoder
description: Spreadsheet files decoder
version: 0.3.0
authors:
- Stéphane Este-Gracias <sestegra@gmail.com>
homepage: https://github.com/sestegra/spreadsheet
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  archive: '^1.0.20'
  xml: '^2.4.0'
dev_dependencies:
  test: '^0.12.0'
