name: spreadsheet_decoder
description: Spreadsheet files decoder
version: 1.0.0
authors:
- Stéphane Este-Gracias <sestegra@gmail.com>
homepage: https://github.com/sestegra/spreadsheet

environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dependencies:
  archive: ^2.0.0
  xml: ^3.0.0

dev_dependencies:
  test: ^1.2.0
